#use node_js
language: node_js

#define node js version to use
node_js:
  - "node"

#choose branch on commit of which this script should excecute
branches:
  only:
    - main


before_install:
  #install rvm 2.4.1
  - rvm install 2.4.1
  - rvm use 2.4.1
  #set home variables
  # - . $HOME/.nvm/nvm.sh && nvm install 10.13 && nvm use 10.13 
  #install gems through bundler
  - gem install bundler 
  #if gems are missing this script will get the missing gems.
  - bundle check || bundle install 

install:
  #install firebase tools, required to deploy on firebase hosting 
  - npm install -g firebase-tools 


# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: 
  #continue even after error
  - set -e 
  #build jekyll site
  - jekyll build 

after_success:
  #deploy to firebase using stored token. 
  - firebase deploy --token "${FIREBASE_API_TOKEN}" 

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - secure: XE5xvfqsXBr+34D0+HmybxX3FkwOrigM9am9lEh2bth6UExcx18sKgrwn3lRLJkO0SHizSj3ECtsidd2nAjuywL5MD8/vMiQLLOryRC8h+uDoAFcilckRoNJd1TSCIsbhptflMKi+Yraj+RLpAM4yqKKJHGQoeT2k0La3ElZtY98/jkF6jlmA3fleRkETCm4NRlkr1B4rXvEQth+vEkOH+OzQ7XN/tV8bQevrY63HlsH0E7RWgIZN8ohsAfJ+Llsxm/QB6OECDqnhR3N9iLhRVtMJxpV3sQlstVRNhDbr4Gk0zcBH2abhFyvchzR/Vbt/6W8fGDpbiHkK6TnBJspj8C4ALh6MJaGZtKtvpTJK/3eKEqXMlGNUDDSr8iVLtEZeB8b5hlTjOwk5FRqcXVzgQ2/phREqHdftuTZZOLtwdcqCFJwIUUB7D2VdpE5U98S2g9Lib+O5Iw3XOqkTJzc/0gzoaTa10czqzn29MhJoOzAAvsHeukUw45dPiXC84HDLUvD9Mw0ClNzrXdb5oCGtFMJjzYFkLPxNFPOTvTimPTy9mQTr4qtRD/lbPS3sqJV7u0pFNItXNAu1aPaDFbyQpHqZDa+ZCI75+uAe5e2YV8g/VoMYQOt3/JJcZ2jEOR6yxITKiyEl3rHj0Ybic66b2NfN2UYda9N5wkDgE/pHbo=

sudo: false # route your build to the container-based infrastructure for a faster build
